- name: Instala cron job (ansible-pull) con ejecucion 15 minutos
  cron:
    user: ansible
    name: "Proveedor ansible"
    minute: "*/15"
    job: "/usr/bin/ansible-pull -o -U https://github.com/gussietorres/ANSIBLE.git > /dev/null"
