- name: Instala cron job (ansible-pull) con ejecucion 15 minutos
  cron:
    user: root
    name: "Proveedor ansible"
    minute: "0 23"
    job: "/usr/bin/ansible-pull -U https://github.com/gussietorres/ANSIBLE.git > /dev/null"
