- name: Instala cron job (ansible-pull) con ejecucion a las 23:00 de cada día
  cron:
    user: root
    name: "Proveedor ansible"
    minute: "0 23"
    job: "/usr/bin/ansible-pull -U https://github.com/gussietorres/ANSIBLE.git > /var/log/ansible.log"
