- name: Crea usuario ansible
  user:
    name: ansible
    system: yes

- name: Inserta usuario ansible en grupo sudoers, copiado /files/sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
